version: '3.8'

networks:
  elk:
    name: elk
    driver: bridge

services:
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    networks:
      - elk
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200